### ISSUE TITLE
SNAPSHOT and addQualifier

### ISSUE THREAD

**Issue by nedtwigg** [stempler/bnd-platform#13]
How hard would it be to add logic which sets addQualifier to true iff the version ends in `SNAPSHOT`?

**Comment by stempler** [comment]
Did you try configuring it in a global bnd configuration closure?
Something like this:

```groovy
platform {
    bnd {
        if (version.endsWith('SNAPSHOT') {
            addQualifier = true
        }
    }
}
```

**Comment by nedtwigg** [comment]
Thanks for the hint!  This is where I ended up:

The snapshot jars in question already have OSGi headers (with version 1.0.0.SNAPSHOT), so the first step was to manually specify a group.

```groovy
bnd(group: 'com.diffplug.durian') {
	if (version.endsWith('SNAPSHOT')) {
		useBndHashQualifiers = true
		addQualifier = true
	}
}
```

But after thinking a little more, I the problem is probably upstream.  When I'm publishing a snapshot jar with OSGi metadata, I should probably have it append a date qualifier rather than SNAPSHOT in the OSGi bundle anyway..

**Comment by stempler** [comment]
Also, the bndHashQualifier is solely based on the configuation within bnd-platform for a bundle. This was intended to bypass the Eclipse RCP Target Platform caching mechanism when for instance the imported packages have changed.

You can use a closure though to generate a custom qualifier. That one could then be based on a build timestamp.

**Comment by missedone** [comment]
Hi @stempler
Do you have a concrete example to replace SNAPSHOT with timestamp qualifier ?
We are seeking a way to do it for testng: https://github.com/testng-team/testng-p2/issues/10

My current thought is to do something like this 
```
bnd {
if (version.endsWith("SNAPSHOT")) {
version = version.subString(...) + "." + getTimestamp()
}
}
```
Thanks
