### ISSUE TITLE
Be very useful if bundle could support transitive = false

### ISSUE THREAD

**Issue by walker99** [stempler/bnd-platform#16]
Trying to accomplish a merge of two bundles, one of which has a broken transitive dependency e.g.

```
        // Excluding transitive doesn't seem supported
        bundle ("org.apache.xmlbeans:xmlbeans-xpath:$version") {
            transitive = false
        }
```

Example file attached - [build.gradle.txt](https://github.com/stempler/bnd-platform/files/447865/build.gradle.txt)

The issue is caused by xmlbeans-xpath, which has a well known broken dependency to a saxon-9 version that is not available under the same name any more.

Very new to both Gradle, Groovy, and bnd-platform so there may be ways to do this I don't know of. Also, I'd offer to pitch in to help code it - but same problem applies!

**Comment by walker99** [comment]
So it seems I found a (possibly intended) workaround by including the required JARs as platform dependencies with the transitive setting false, and then using the match = syntax of merge to bring in the artifacts

```
version = '2.4.0'   

dependencies {
     platform compile ( "org.apache.xmlbeans:xmlbeans:$version" )  {
         transitive = false;
     }
     platform compile ( "org.apache.xmlbeans:xmlbeans-xpath:$version" ) {
         transitive = false;
     }
}
 
platform {
    merge (collectServices: true) {
        
        bnd {
            instruction 'Export-Package', "!*.txt, !repackage, !schemaorg_apache_xmlbeans, org.apache.xmlbeans.*;version=$version"
            instruction 'Import-Package', "!org.apache.tools.ant.*, !org.apache.crimson.jaxp, *"
        }
        
        // Use match syntax as can't include transitive inside merge block - does
        // correctly find and match earlier platform dependencies
        match {
            it.group == 'org.apache.xmlbeans'
        }        
   }
}
```

I'll leave this open for review/further comment, but I'm not sure any actual fix is needed. It might be useful to include the model above in the User docs though - as a newbie, it took me quite some time to figure out. Could save others the same legwork.

**Comment by walker99** [comment]
Stumbled across another solution to this, which I think is a bit neater:

```
/* 
 * Ignore these as dealt with elsewhere
 */
configurations {
    platform.exclude group: 'stax'
    platform.exclude group: 'net.sf.saxon'
}

platform {
    merge (collectServices: true) {
        bundle "org.apache.xmlbeans:xmlbeans:$version" 
        bundle "org.apache.xmlbeans:xmlbeans-xpath:$version" 
```

**Comment by stempler** [comment]
Yes, it is intended to deal with this kind of issue with the options provided in the Gradle dependency management. Your two examples demonstrate two examples for that quite well. Thanks!

**Comment by walker99** [comment]
Cool - have been involved with OSGi for years, so I know that model well. Gradle is still very new to me!
