### ISSUE TITLE
Download bundles from existing p2 sites

### ISSUE THREAD

**Issue by ocroquette** [stempler/bnd-platform#18]
Hi Simon,

first of all, thanks a lot for your plugin, it's really useful and easy to use!

Quick question: is it possible to download bundles from existing p2 sites? The idea would be to clone parts of them to be more independent and/or merge several sources into a single p2 sites.

**Comment by stempler** [comment]
Hi Olivier,

interesting idea. That's nothing that is included yet. Use case is usually to combine the different sites later (for instance in the Eclipse target platform definition). But I can understand why one may not want to rely for instance on the official Eclipse update sites.

One possible solution could be "mavenizing" the update site and then including the Maven dependencies in your bnd-platform build. There is [unpuzzle](https://github.com/akhikhl/unpuzzle) that could be used for that. I also have a [fork where I extended unpuzzle](https://github.com/stempler/unpuzzle), though for a slightly different use case.

Another thing you might want to look into is [Goomph](https://github.com/diffplug/goomph), it orchestrates OSGi builds in Gradle, and uses both dependencies from p2 update sites and from Maven (via bnd-platform).

@nedtwigg Any ideas on what would be the best approach here?

**Comment by nedtwigg** [comment]
If you want to manipulate P2 repositories in a repeatable way, I'd recommend Goomph's [P2Model](https://diffplug.github.io/goomph/javadoc/3.3.0/com/diffplug/gradle/p2/P2Model.html).  Here's an example:

```gradle
P2Model model = new P2Model();
model.addRepo('https://someRepo/')
model.addIU('someIU')

// to mirror just the selected part of the p2 repository using the p2.mirror ant task
P2AntRunner runner = model.mirrorApp(new File('destinationFolder'))
runner.runUsingBootstrapper()

// or to install some p2 application using p2director
model.addFeature('org.eclipse.sdk.ide')
DirectorApp director = model.directorApp(new File( 'installFolder'), 'profileName')
director.installFeatures()
director.platform(SwtPlatform.getNative())
director.runUsingBootStrapper()
```

If you want to mavenize, Goomph can do that [direct from a p2 repository](https://diffplug.github.io/goomph/javadoc/3.3.0/com/diffplug/gradle/p2/AsMavenPlugin.html).  Here's an [example project](https://github.com/diffplug/gradle-and-eclipse-rcp) that ties a lot of the pieces together.

**Comment by ocroquette** [comment]
@nedtwigg great, thank you! I gave the first option a try, and it works. I have a few questions if you don't mind:

1. it looks like it downloads every available version for each plugin. Is there a way to limit the download to a specific version?
1. is there a way to see live what files are getting downloaded? I tried the -d option of Gradle, but it doesn't seem to have any effect
1. if the mirrorApp() is started again, willl it download only new data?

**Comment by nedtwigg** [comment]
> 1. it looks like it downloads every available version for each plugin. Is there a way to limit the download to a specific version?

Yup, `model.addIU('someIU', 'someVersion')`.  Same for features.  [javadoc](https://diffplug.github.io/goomph/javadoc/3.3.0/com/diffplug/gradle/p2/P2Model.html).

> 2. is there a way to see live what files are getting downloaded? I tried the -d option of Gradle, but it doesn't seem to have any effect

Nope.  It's running an eclipse headless application which doesn't have any console logging flags (at least not that I could find).

> 3. if the mirrorApp() is started again, willl it download only new data?

Correct.

**Comment by stempler** [comment]
Thanks @nedtwigg  for the example. Provides a great quick start for someone that needs this kind of functionality.

@ocroquette I'm closing this issue now, please reopen if there are any remaining issues.

**Comment by ocroquette** [comment]
Sorry I didn't provide feedback yet, we didn't have time yet to test the latest comments from @nedtwigg , but the ticket can definitely be closed. Many thanks to both of you for your help, it is much appreciated!
