### ISSUE TITLE
Additional configuration of update site result

### ISSUE THREAD

**Issue by dannmartens** [stempler/bnd-platform#24]
Hi, 

This simply is a great Gradle plug-in!

Is there any way to rename the category heading "Target platform"? 

Cheers,
 Dann

**Comment by missedone** [comment]
yes, you can, for example:

```groovy
platform {
    categoryName 'TestNG P2 Libraries'
    categoryId 'org.testng.p2.libraries'
}
```

see more details about the parameters: https://github.com/stempler/bnd-platform#plugin-settings

**Comment by dannmartens** [comment]
Cool! Works for me!
