### ISSUE TITLE
Can't create feature dependencies

### ISSUE THREAD

**Issue by HaasJona** [stempler/bnd-platform#26]
It seems to be impossible to add a "<requires>" block to the feature.xml. For example I have feature A which includes plugins a, b, c and I have feature B which includes plugin d, that depends on a and b. 

Currently, feature B will automatically include plugins a, b and d, but in my case I would prefer it if feature B would only include plugin d and have an additional dependency on feature A.

Is this possible?

**Comment by stempler** [comment]
Does a configuration like this add the `<requires>` tag you refer to?

```groovy
platform {
    // define a feature
    feature(...) {
        ...

        // include a feature that is defined elsewhere given its ID
        includes << 'some.other.feature'
    }
}
```

Probably the feature will still reference *a* and *b* directly as well, so there might be changes necessary to do some processing when the feature is assembled, to check for bundles already present in included features.

Or, more comfortable, a mode where features are checked for their content and dependencies in features delegated preferably to other features. But that would very likely be a lot more work than the other option. Also, your case would not be a straightforward use case, as the dependency to the feature includes an additional dependency to *c* that seems to be not required for feature *B*.

**Comment by HaasJona** [comment]
No, that adds a <includes> block, not a <required> block. See documentation here: http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Ffeature_manifest.html

**Comment by stempler** [comment]
Well, then I'm afraid there is no mechanism there right now for handling that.

Where does `includes` and `requires` make a difference? If I understand the docs correctly mainly in the aspect that `requires` may refer to a feature that is defined in a different update site.

I guess in that case there would be the need to be able to configure that for a feature and use the Gradle dependency mechanism to exclude those dependencies that are provided via the foreign feature from the update site.

**Comment by HaasJona** [comment]
We want to be more flexible on who provides feature A and which updatesite is hosting it. Also feature A might be available in multiple versions and including the feature seems to make the dependency more tightly coupled.

**Comment by stempler** [comment]
If you are willing to have a look at that, pull requests are always welcome. I'm afraid I don't really have much leisure time to work on things like this, but I am happy to provide support where I can.

If in sense of changes to the plugin adding the `requires` configuration for a feature is the only thing that needs to be done, that should be mainly:
- supporting the configuration of a feature with the necessary information ([entry point here](https://github.com/stempler/bnd-platform/blob/master/src/main/groovy/org/standardout/gradle/plugin/platform/PlatformPluginExtension.groovy#L348))
- include the respective section when writing the `feature.xml` file ([FeatureUtil](https://github.com/stempler/bnd-platform/blob/master/src/main/groovy/org/standardout/gradle/plugin/platform/internal/util/FeatureUtil.groovy))

**Comment by HaasJona** [comment]
Thank you, I will take a look at that.
