### ISSUE TITLE
Cannot exclude plugins from feature

### ISSUE THREAD

**Issue by Treehopper** [stempler/bnd-platform#28]
Thanks for contributing this great tool! It worked perfectly for me so far, but I stumbled over one issue.

Using the 'exclude group' statement for a plugin in a defined feature seems to have no effect, or I maybe misunderstood its purpose.
I created a minimal example to illustrate this:

	buildscript {
		repositories {
			jcenter()
			maven {
				url "https://plugins.gradle.org/m2/"
			}
		}
		dependencies {
			classpath 'org.standardout:bnd-platform:1.4.0'
		}
	}

	apply plugin: 'org.standardout.bnd-platform'

	repositories {
		mavenCentral()
	}

	dependencies {
		platform 'org.codehaus.groovy.modules.http-builder:http-builder:0.6'
	}

	platform {
		bundle 'org.codehaus.groovy.modules.http-builder:http-builder:0.6'

		feature(id: 'platform.restclient', name: 'REST client dependencies', version: '1.0.0') {
			 // define what's in the feature
			 plugin 'org.codehaus.groovy.modules.http-builder:http-builder:0.6', {
				 // exclude this transitive dependency
				 exclude group: 'net.sourceforge.nekohtml', module: 'nekohtml'
			}
		}

		// If you have an Eclipse installation available, you may want to set the env. variable
		// ECLIPSE_HOME with its path, that will prevent the BND plugin to download it.
		// As of today, the version downloaded by default is:
		// http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/indigo/SR2/eclipse-rcp-indigo-SR2-win32-x86_64.zip
		if ( System.getenv("ECLIPSE_HOME") != null )
			eclipseHome  = new File(System.getenv("ECLIPSE_HOME"))
	}

This should create an update site with a feature, composed of all transitive dependencies of the http-builder, except 'net.sourceforge.nekohtml'. Right?
However, in the resulting feature.xml I find the following:

    <plugin id="net.sourceforge.nekohtml" download-size="0" install-size="0" version="1.9.16.bnd-y0MRJw" unpack="false" />
    <plugin id="net.sourceforge.nekohtml.source" download-size="0" install-size="0" version="1.9.16.bnd-y0MRJw" unpack="false" />

I use these commands to run the build:

    export ECLIPSE_HOME="C:/your_eclipse_install"
    gradle updateSiteZip

**Comment by stempler** [comment]
You have the dependency to the http-builder module defined both via `platform.bundle` and `platform.feature.plugin`. Try removing the `platform.bundle` definition (which does not have the exclude).

The exclude is actually a mechanism of Gradle core, you can check the dependencies that Gradle resolves for your project with `gradle dependencies`. Check there (platform configuration) if the excluded dependency is still there and if so, where it shows up.

**Comment by Treehopper** [comment]
Thanks for your quick reply!
I have modified my build.gradle as follows:

	buildscript {
		repositories {
			jcenter()
			maven {
				url "https://plugins.gradle.org/m2/"
			}
		}
		dependencies {
			classpath 'org.standardout:bnd-platform:1.4.0'
		}
	}

	apply plugin: 'org.standardout.bnd-platform'

	repositories {
		mavenCentral()
	}

	dependencies {
		platform 'org.codehaus.groovy.modules.http-builder:http-builder:0.6'
	}

	platform {
		feature(id: 'platform.restclient', name: 'REST client dependencies', version: '1.0.0') {
			 // define what's in the feature
			 plugin 'org.codehaus.groovy.modules.http-builder:http-builder:0.6', {
				 // exclude this transitive dependency
				 exclude group: 'net.sourceforge.nekohtml', module: 'nekohtml'
			}
		}

		// If you have an Eclipse installation available, you may want to set the env. variable
		// ECLIPSE_HOME with its path, that will prevent the BND plugin to download it.
		// As of today, the version downloaded by default is:
		// http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/indigo/SR2/eclipse-rcp-indigo-SR2-win32-x86_64.zip
		if ( System.getenv("ECLIPSE_HOME") != null )
			eclipseHome  = new File(System.getenv("ECLIPSE_HOME"))
	}

But this doesn't seem to fix it. I'm still getting the `net.sourceforge.nekohtml` entry in the restclient feature.
This is the output of `gradle dependencies`.

	------------------------------------------------------------
	Root project
	------------------------------------------------------------

	platform
	\--- org.codehaus.groovy.modules.http-builder:http-builder:0.6
		 +--- org.apache.httpcomponents:httpclient:4.2.1
		 |    +--- org.apache.httpcomponents:httpcore:4.2.1
		 |    +--- commons-logging:commons-logging:1.1.1
		 |    \--- commons-codec:commons-codec:1.6
		 +--- net.sf.json-lib:json-lib:2.3
		 |    +--- commons-beanutils:commons-beanutils:1.8.0
		 |    |    \--- commons-logging:commons-logging:1.1.1
		 |    +--- commons-collections:commons-collections:3.2.1
		 |    +--- commons-lang:commons-lang:2.4
		 |    +--- commons-logging:commons-logging:1.1.1
		 |    \--- net.sf.ezmorph:ezmorph:1.0.6
		 |         \--- commons-lang:commons-lang:2.3 -> 2.4
		 +--- org.codehaus.groovy:groovy:1.8.8
		 |    +--- antlr:antlr:2.7.7
		 |    +--- asm:asm:3.2
		 |    +--- asm:asm-commons:3.2
		 |    |    \--- asm:asm-tree:3.2
		 |    |         \--- asm:asm:3.2
		 |    +--- asm:asm-util:3.2
		 |    |    \--- asm:asm-tree:3.2 (*)
		 |    +--- asm:asm-analysis:3.2
		 |    |    \--- asm:asm-tree:3.2 (*)
		 |    \--- asm:asm-tree:3.2 (*)
		 +--- net.sourceforge.nekohtml:nekohtml:1.9.16
		 |    \--- xerces:xercesImpl:2.9.1
		 |         \--- xml-apis:xml-apis:1.3.04
		 \--- xml-resolver:xml-resolver:1.2

	platformaux
	No dependencies

**Comment by stempler** [comment]
Ah yes, exactly, the dependency was actually added three times.
