### ISSUE TITLE
Flag to disable import mecanism during p2 repository creation ?

### ISSUE THREAD

**Issue by reyman** [stempler/bnd-platform#29]
Hi,
I'm using bnd-platform to create a self contained eclipse-plugin bundle using `conditionalpackage` expression, as you can see in my `build.gradle` into plugin folder : 

```
dependencies {
    compile 'p2:ummisco.gama.annotations:+'
    compile 'p2:msi.gama.core:+'
    compile 'org.genstar:genstar-core:1.0'
    compile 'org.genstar:genstar-spll:1.0'
    compile 'org.genstar:genstar-spin:1.0'
    compile 'org.genstar:genstar-gospl:1.0'
}

apply plugin: 'com.diffplug.gradle.osgi.bndmanifest'
osgiBndManifest {
    copyTo 'META-INF/MANIFEST.MF'
}

// configure the OSGi bundle
jar.manifest.attributes(
        '-exportcontents': 'core.*, gospl.*, spin.*, spll.*',
        '-removeheaders': 'Bnd-LastModified,Bundle-Name,Created-By,Tool,Private-Package,Require-Capability',
        '-conditionalpackage': '!org.w3c.*, !org.xml.*, !javax.*, *',
        'Import-Package': '!org.w3c.*, !org.xml.*, !javax.*,*',
        'Bundle-Version': '1.0.0.${tstamp}',
        'Bundle-SymbolicName': project.name,
        'Bundle-RequiredExecutionEnvironment': 'JavaSE-1.8',
        'Require-Capability': 'osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"',
        'Bundle-Vendor': 'Gama team',
        'Bundle-License': "http://www.apache.org/licenses/LICENSE-2.0"
)
```

But, ben i launch `gradle clean updatesite`, bnd-platform create a p2 repository with all transitive dependencies. I don't need all this dependencies because my bundle contain all the class needed for the runtime. I want to produce p2 repository with only this self contained bundle, so, is there a flag or something to desactivate this option into bnd-platform ?

**Comment by stempler** [comment]
How you add your bundle to the bnd-platform configuration? What mechanism are you using?

Are you adding it as Maven dependency? Then there would be two options
- add it to the platformaux configuration instead of the platform configuration or
- explicitly exclude the dependencies (via the corresponding Gradle syntax for that)

**Comment by reyman** [comment]
Perhaps this is more clear if i give you all information using the github link : https://github.com/ANRGenstar/gamaplugin

I'm using the [goomph gradle plugin](https://github.com/diffplug/goomph), which also use bnd-platform, to download p2 (build.gradle of target.p2 folder) and maven (build.gradle of target.maven folder) dependencies used for my eclipse-plugin `src/` compilation (`genstar.plugin.bundle-all` folder).

**Comment by stempler** [comment]
I'm not so familiar with this kind of setup.The dependency seems to be added [here](https://github.com/ANRGenstar/gamaplugin/blob/master/target.maven/build.gradle#L22) to the bnd-platform configuration. Project dependencies behave a bit differently than Maven dependencies, so that's often not so easy to deal with.

You could try to change `platform` to `platformaux` in [line 22](https://github.com/ANRGenstar/gamaplugin/blob/master/target.maven/build.gradle#L22). Not sure if that will work.

As an alternative you could exclude the dependencies you want to exclude similar to [line 18](https://github.com/ANRGenstar/gamaplugin/blob/master/target.maven/build.gradle#L18).
With `gradle dependencies` you can check what dependencies are listed for the platform configuration.

**Comment by reyman** [comment]
I try to change `platform` to `platformaux` without success : 

```
* What went wrong:
A problem occurred evaluating project ':target.maven'.
> java.lang.NullPointerException (no error message)
```

I try the alternative by excluding manually.

As maven permits, is it possible to push the p2repository by ssh using gradle after that ?

**Comment by nedtwigg** [comment]
I think there's a little confusion.  `goomph` and `bnd-platform` are separate projects - they don't depend on each other, but they do complement each other.

The `jar.manifest.attributes` stuff that you're mentioning above, that gets used by `com.diffplug.gradle.osgi.bndmanifest`, not by `bnd-platform`.  `bndmanifest` is Goomph plugin that uses bnd to generate manifests for the plugin YOU are developing.  `bnd-platform` is this plugin, which downloads dependencies from maven and calls bnd to wrap YOUR DEPENDENCIES with appropriate OSGi metadata.  Apparently it also has some updatesite functionality, but I don't know much about it.

Looking at your source, I think you're mixing up the place where you download your dependencies from maven, with the place where you can publish your result.

I think you want to make a separate project `publish`, by adding a line to your `settings.gradle` file.  I bet something close to this will work for you as the build.gradle for that:

```gradle
configurations {
    platformaux
}

dependencies {
    platformaux project(':genstar.plugin.bundle-all')
}

apply plugin: 'org.standardout.bnd-platform'
```

**Comment by reyman** [comment]
Thanks for you help @nedtwigg and @stempler !

I separate the project like you propose : 
```

── build.gradle
├── build.properties
├── genstar.plugin.bundle-all
│   ├── build
│   ├── build.gradle
│   ├── build.properties
│   ├── META-INF
│   └── src
├── genstar.plugin.platform
│   ├── build
│   ├── build.gradle
│   └── build.properties
├── gradle
│   └── wrapper
├── gradlew
├── gradlew.bat
├── settings.gradle
├── target.maven
│   ├── build
│   └── build.gradle
├── target.p2
│   ├── build
│   ├── build.gradle
│   └── workspace
└── workspace

```

This is not perfect, i run first `gradle build` to build my unique jar `genstar.plugin.bundle-all.jar`, then `cd genstar.plugin.platform`, then `gradle updateSite` to generate p2 site.

I remove all `import-package` into osgi bundle of my unique jar `genstar.plugin.bundle-all.jar`. In the future i certainly try to mix the two approaches in platform folder/subproject, by making somme dependencies (`Import Package`) as `Optional`, and ask to `bnd-platform` to wrap these optional dependencies and include them with into p2 repository with  `genstar.plugin.bundle-all.jar` .
