### ISSUE TITLE
random jar artifact converted to bundle

### ISSUE THREAD

**Issue by HaasJona** [stempler/bnd-platform#30]
The plugin [here](https://github.com/stempler/bnd-platform/blob/83a5235bc8afa76d69c4e020cab68b9a2fd800de/src/main/groovy/org/standardout/gradle/plugin/platform/internal/BundlesAction.groovy#L85) only checks the extension of the artifact, but if you have multiple jar artifacts with the same id (for example one containing the main program and one containing tests), bnd-plattform chooses a random one to create a bundle. My hacky workaround:

    if (it.extension == 'jar' && it.type == 'jar') {

**Comment by stempler** [comment]
Wouldn't you just define what you want in the dependency, if you have different artifacts? Or do you mean something different?

e.g. `bundle group: 'com.github.jnr', name: 'jffi', classifier: 'native'` for getting the *native* Jar of [this dependency](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.jnr%22%20AND%20a%3A%22jffi%22)

**Comment by HaasJona** [comment]
In this case it's a dependency on another subproject of the same gradle build, so I can't set a classifier on the dependency. (also the classifier for all the artifacts are null)
