### ISSUE TITLE
How to remove dependency while creating p2 update site?

### ISSUE THREAD

**Issue by tsjfd** [stempler/bnd-platform#35]
I need an osgi bundle from a maven artifact. Due to the automatic dependency resolution I get log4j in a different version and with a different group id in my generated p2 repository. I don't get it how I can stop bnd-platform from creating a bundle for log4j. The documentation says "Both notations support adapting the dependency configuration as supported by Gradle, e.g. **excluding specific transitive dependencies**." but how can I achieve this (e.g. for the example in the doc.)?

```
platform {
    // add pegdown as dependency to the platform configuration
    bundle 'org.pegdown:pegdown:1.4.2'
}
```
Sorry for the stupid question.

**Comment by missedone** [comment]
you can use `exclude`, 
see example [[1]](https://github.com/testng-team/testng-p2/blob/master/build.gradle#L75), or [[2]](https://github.com/stempler/bnd-platform#defining-features-since-11)

**Comment by tsjfd** [comment]
Thx, this helped me a lot!
