### ISSUE TITLE
Handling of "optional" dependencies

### ISSUE THREAD

**Issue by qqilihq** [stempler/bnd-platform#37]
I'm currently introducing bnd-platform in our project and stumble across the "optional dependencies".

I've already seen [this existing issue](https://github.com/stempler/bnd-platform/issues/19) and I understand the reasons, that the information about a dependency being optional gets lost.

Our situation: We have a comparatively large dependency tree and the only way to work around this issue which I've found so far is to repeatedly apply trial-and-error, i.e.:

1) Build the update site
2) Load it into Eclipse's target platform
3) Try to launch my app
4) Get an `org.osgi.framework.BundleException` with the `Unresolved requirement` package being mentioned
5) Add that package to the `optionalImport` configuration in my `build.gradle`
6) GOTO 1)

Are there any more elegant workarounds or am I overlooking something? Probably this problem should be addressed completely different on our side? Any feedback or suggestions are very welcome!

**Comment by stempler** [comment]
That workflow looks familiar. I did not really find a better for that problem as well.
Though you can use the *Target Platform State* view to inspect all current problems (use *Show only unresolved* in the view menu). Maybe that allows you to tackle more packages at once, w/o the need of frequent rebuilds.

**Comment by qqilihq** [comment]
Great, thanks for the tip. Good to know that I'm not doing it in an entirely stupid way :)

**Comment by SimonScholz** [comment]
I know this issue is already closed, but I like to mention the new task I added, which is called potentialOptionalImports and can be used like this:

`./gradlew pOI`

See https://github.com/stempler/bnd-platform#optional-dependencies for further details.

And maybe there is hope in the current gradle 4.6 release:

https://docs.gradle.org/4.6/release-notes.html#support-for-optional-dependencies-in-pom-consumption

**Comment by qqilihq** [comment]
@SimonScholz That sounds awesome and will for sure come in handy when I need to extend my build configuration the next time! Thanks for your efforts!
