### ISSUE TITLE
Create multiple features with different content

### ISSUE THREAD

**Issue by fipro78** [stempler/bnd-platform#39]
Hi,

I would like to create multiple features inside one update site. The platform feature should be the "All" feature containing everything specified with transitive dependencies, additionally there should be a feature without some transitive dependencies.

I thought of something like this (the plugin names are fictive):

```
platform {
    categoryId = 'fipro'
    categoryName = 'fipro'

    featureId = 'org.fipro.something.feature'
    featureName = 'fipro All'
    featureVersion = "1.0.0"
    featureProvider = 'Dirk Fauth'

    defaultQualifier = ''
    useBndHashQualifiers = false
    useFeatureHashQualifiers = false
    defaultQualifierMap.prefix = ''

	feature(id: 'org.fipro.sub.feature', name: 'fipro without slf4j') {
		plugin "org.fipro:fipro-service:1.0.0", {
			// exclude this transitive dependency
			exclude group: 'org.slf4j', module: 'slf4j-api'
		}
	}

	feature(id: 'org.fipro.something.feature', name: 'fipro All') {
		plugin "org.fipro:fipro-service:1.0.0"
	}
}
```

This should be possible with p2, but the generated feature.xml files are equal. It looks like the bundles that are configured in the feature.xml are simply a collection of all bundles in the bundles directory. The exclude is not taken into account on creating the xml file, only on downloading.

If you can give us a pointer on how this can be fixed, we could try to provide a pull request.

Greez,
Dirk

**Comment by stempler** [comment]
The way it works right now is that there is one Gradle dependency configuration that backs the dependencies. The `plugin` instruction is just delegating to the Gradle mechanism for adding a dependency. That means in this case the dependency is added twice.

The exclude is interpreted by the Gradle dependency mechanism and excludes the module from the configuration.The second time the dependency is added slf4j is added to the configuration (and thus voids the exclude). Later when the feature is assembled, there is no info about the exclude, just everything associated to the plugins included in the feature is added.

A workaround might be manipulating the [feature](https://github.com/stempler/bnd-platform/blob/master/src/main/groovy/org/standardout/gradle/plugin/platform/internal/Feature.java) objects before the feature Jars are written in task [bundleFeatures](https://github.com/stempler/bnd-platform/blob/master/src/main/groovy/org/standardout/gradle/plugin/platform/PlatformPlugin.groovy#L161). Could work well at least when the bundles to remove don't have transitive dependencies.
Right now I'm afraid I don't have a good idea for a better solution.

**Comment by fipro78** [comment]
It turned out that the issue is

a) `generatePlatformFeature` is set to `true` by default
b) one of the features has the same id as the platform feature

This was explained in #65 also.

I therefore close this issue, as by setting `generatePlatformFeature` to `false` solves this issue.
