### ISSUE TITLE
Question about re-wrapping bundles

### ISSUE THREAD

**Issue by Andy-L** [stempler/bnd-platform#4]
Is there a way to programmatically modify the imports in a bundle?  I'm re-wrapping a bundle in order to modify some of its imports to change the versioning from MAJOR to MINIMUM.  Right now I'm doing that by specifying a ```bnd```  closure in which I'm using an ```instruction 'Import-Package'``` to re-specify all of its imports.

I was wondering if there was a way to do this more like the custom version example in the README. I'd like to apply a versioning scheme to the imports of a bundle, filtering it to a subset of its imports using a group specification.

**Comment by stempler** [comment]
The thing that comes closest to what you want to do is `prependImport`. It replaces all matching imports it finds, but leaves others like they are. However, you are not able to access the original import (or its version) directly. With `prependImport` you can do something like this (replacing the version with a fixed version):

```groovy
bnd {
  prependImport "org.thatlibrary.*;version=[1.2.3,2)"
}
```

But in principle, it is possible to access the existing instructions - just take a look at the implementation of `prependImport` in the [BndConfig](https://github.com/stempler/bnd-platform/blob/master/src/main/groovy/org/standardout/gradle/plugin/platform/internal/config/BndConfig.groovy) class. With some work it should be possible to add an operation to adapt versions of specific packages.

**Comment by stempler** [comment]
@Andy-L was that any help to you?
Currently I don't really have the time to work on that. If you want to give it a try, you're more than welcome.

**Comment by Andy-L** [comment]
For the moment, I've got the dumb thing working so I'll leave it until I have time to come back and noodle on it some more. Thanks for the help.
