### ISSUE TITLE
Only transitive dependencies being bundled without parent plugin

### ISSUE THREAD

**Issue by Daubinrue** [stempler/bnd-platform#41]
It seems that there may be a bug where certain plugins are not being added to the bundle, but the parent plugin's transitive dependencies are. Ex: 

`platform{
	feature(id: 'platform.plugins', name: 'P2 update site Plugins') {
		plugin (group: 'eclipse.plugins', name: 'manager-handle', version: '+')
}`

When the updatesite task is run, the plugin 'manager-handle' shows in build/plugins as expected. When I dive into the build/updatesite/plugins dir it is not there. However, all of it's transitive dependencies are. 
I also checked the artifact.xml and it is not showing there as well, just the transitive dependencies. No errors display on build. This behavior does not occur with every plugin, but certain ones have this issue. I have checked POMS and do not notice any difference between them. I know you may not have time to fix or look into this issue, but it would be greatly appreciated if you could lend me some ideas or point me to somewhere to look into for this issue. Thanks a lot for the help!

**Comment by Daubinrue** [comment]
Update on this one. So it turns out that the manifest is not being read correctly. I tried deleting it and using a blank manifest and the plugin was pulled into the update site this time. Still looking into the root cause.

**Comment by stempler** [comment]
Could it be that the dynamic dependency version is an issue? Does it make a difference if you use a concrete version?
