### ISSUE TITLE
About updateSite run from root folder ? 

### ISSUE THREAD

**Issue by reyman** [stempler/bnd-platform#44]
This is more a question than an issue, i have a strange behavior in my program which use `bnd-platform` and `goomph` in parallel.

I have multiple folders in the project : 
- **target.p2** from goomph which take apply `com.diffplug.gradle.p2.asmaven` and downloads dependencies from a p2 repository and makes them available in a local maven repository
- **target.maven** wrap maven jar dependencies downloaded to osgi bundle using bnd-platform
- **genstar.plugin.bundle-all** compile the sources using all maven sources ( downloaded from p2 + maven)
- **genstar.plugin.bundle-all** create and deploy the plugin/features eclipse site with **genstar.plugin.bundle-all** jar using bnd-platform **updateSite** task

When i run `gradle updateSite` from the root folder in my project ([git source here](https://github.com/ANRGenstar/gamaplugin)), this is the `target.maven:updateSite ` which is launched and not the folder `genstar.plugin.platform` which contain the `platform` definition of `org.standardout.bnd-platform`

The build download bad dependencies and failed with this error : [#2200](https://github.com/bndtools/bnd/issues/2220) and [#40](https://github.com/diffplug/goomph/issues/40)

When i launch in root `genstar.plugin.platform:updateSite` or enter in the folder `genstar.plugin.platform` and i run 'gradle:updateSite`, all works fine ...

There is something i really don't understand, do you have an idea of the problem in my bnd-platform comprehension ? 

Thanks

**Comment by stempler** [comment]
Maybe a multi-project issue? You should be able to run the task on your subproject by [specifying the task with its absolute path](https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:running_partial_build_from_the_root).
