### ISSUE TITLE
Create 1.6 release and publish 1.7 snapshot?

### ISSUE THREAD

**Issue by SimonScholz** [stempler/bnd-platform#51]
Hi Simon,

since a lot of new features came in recently. What do you think of releasing 1.6 and provide 1.7 snapshot on maven central?
I currently always call "./gradlew publishToMavenLocal" and use my "mavenLocal()" repo to use the latest features, but for the the customers of the vogella company it would be great to also make use of the 1.7 snapshot.

Thanks and regards, Simon

**Comment by UrsZeidler** [comment]
We at @SerNet would appreciate this.

**Comment by stempler** [comment]
I'm afraid I don't find as much time for this kind of side projects as I would like to - current state is now released as 1.7.0.
An intermediate 1.6 release is still possible, I'll see if there is any demand.
