### ISSUE TITLE
"Could not retrieve POM" spam

### ISSUE THREAD

**Issue by Tobbe0430** [stempler/bnd-platform#52]
Whenever I execute "./gradlew build", the task :bundles will be followed by a long list of "Could not retrieve POM" followed by a plugin name. The thing is that all these plugins are fetched from a repository that doesn't contain any POM files, which makes the whole task of trying to retrieve POMs a bit unnecessary. 
I wonder if there's a way to prevent the task from trying to retrieve POMs?

Thankful for help.

**Comment by stempler** [comment]
I guess this is what you refer to: https://github.com/stempler/bnd-platform/blob/83a5235bc8afa76d69c4e020cab68b9a2fd800de/src/main/groovy/org/standardout/gradle/plugin/platform/internal/ResolvedBundleArtifact.groovy#L385

What would be your suggestion?
A setting or changing the logging or something else?
