### ISSUE TITLE
Avoid 'Require-Capability' header?

### ISSUE THREAD

**Issue by qqilihq** [stempler/bnd-platform#55]
When processing one of my libs with bnd-platform, suddenly (after an update) there's a `Require-Capability` being added to the `MANIFEST.MF`. This causes trouble, and I'd simply like get rid of it. I already tried something like this:

```
platform {
	bundle 'org.seleniumhq.selenium:selenium-server:3.14.0'
	bnd (group: 'org.seleniumhq.selenium') {
		// trying to strip away the 'Require-Capability',
		// but this does not work, as it is simply being
		// added to the existing one :(
		instruction 'Require-Capability', ''
	}
}
```

Unfortunately, it does not work (see comment). In bnd, there obviously [a switch](https://stackoverflow.com/questions/25851771/in-bndtools-what-causes-a-require-capability-header-for-execution-environment-t) to suppress this, but I'm not sure if/how this can be passed through bnd-platform?

**Comment by stempler** [comment]
There seems to be a bug in bnd (last time I checked that was not resolved yet) where it sometimes generates bad Require-Capability instructions.

You can work aorund it with an instruction like this in the bnd configuration:
```groovy
instruction '-removeheaders', 'Require-Capability'
```

**Comment by qqilihq** [comment]
@stempler Awesome, that worked! Thank you!
