### ISSUE TITLE
Generated update site does not work

### ISSUE THREAD

**Issue by tsjfd** [stempler/bnd-platform#59]
I have tried to apply bnd-platform to my project and managed to create an update site but as soon as I install my Eclipse plugin from the generated update site I get the following error in Eclipse:
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: bar 1.2.3.bnd-ZzR9VQ (foo.feature.group 1.2.3.bnd-ZzR9VQ)
  Missing requirement: bar 1.2.3.bnd-ZzR9VQ (foo.feature.group 1.2.3.bnd-ZzR9VQ) requires 'org.eclipse.equinox.p2.iu; log4j [1.2.16,1.2.16]' but it could not be found
```
My gradle file looks like
```
platform {
	featureId = 'foo'
	featureName = 'bar'
	featureVersion = '1.2.3'
	bundle project(':MyProject')
}
```
Do you have an idea what went wrong or how I can track down the error?

**Comment by SimonScholz** [comment]
Hi @tsjfd ,

it seems that your _MyProject_ also needs _log4j_, which doesn't seem to be part of your target platform.
You could either add _log4j_ as bundle as well or you get it from somewhere else like the orbit repo, which also provides log4j. (https://download.eclipse.org/tools/orbit/downloads/)

Do you have a sample project on Github? Maybe I can guide you then ;-)
