### ISSUE TITLE
Setting buildDir does not work

### ISSUE THREAD

**Issue by abchakra** [stempler/bnd-platform#63]
hi @stempler ,

I want to build out of source , I have set the buildDir=/home/user/p2

 updateSiteDir= new File("/home/user/p2", 'site')

the build directory is created under the project, feature and plugins are in the build directory under the project.

The p2/site folder contains only the artifacts.jar  content.jar .

**Comment by stempler** [comment]
Where do you set the `buildDir`?

The folders are initialised [here](https://github.com/stempler/bnd-platform/blob/bb0d6e9562f5bbee0f9ec38ae90b570855aedd2f/src/main/groovy/org/standardout/gradle/plugin/platform/PlatformPlugin.groovy#L74), when the plugin is applied.

So maybe that's before you change the `buildDir` property. You could try doing it in `gradle.properties` or passing the property to your Gradle command to see if that makes a difference.

**Comment by abchakra** [comment]
I have set the gradle.properties , it worked.
