### ISSUE TITLE
fetchSources = true adds source bundles to feature

### ISSUE THREAD

**Issue by fipro78** [stempler/bnd-platform#65]
Hi,

my understanding of the fetchSources = true feature is

- the sources are downloaded
- source bundles from the downloaded sources are generated or simply used if such bundles already exist
- a source feature is created additionally to the feature

That all works fine. But unfortunately the created/downloaded source jars are also added to the base feature. But they should not be included there. They should only reside in the sources feature to separate function and sources for delivery.

From my understanding it is wrong to add the source jars also to the feature with the deliverables. They should only be part of the generated sources feature.

**Comment by stempler** [comment]
The intent was definitely to have the source bundles only in the source features. An exception to that would be the "platform feature" that includes all bundles.
So I think if source bundles are added to the "normal" features, that's a regression, an untested corner case or maybe due to a change in the Gradle internals.
Which Gradle version are you using?

**Comment by fipro78** [comment]
The build is currently running with Gradle 4.10. Should I try a newer or older version?

**Comment by fipro78** [comment]
BTW, what is a "platform feature" compared to other features? Not sure if I understand that correctly.

My build script basically looks like this:
`platform {
	
    // Add proper path to your eclipse installation (necessary for building a p2 updatesite)
    eclipseHome = new File(eclipse_home)

    // configure proper names for the p2 update site
    categoryId = 'fipro'
    categoryName = 'FiPro Test'

    featureId = 'org.fipro.test.feature'
    featureName = 'Test Services'
    featureVersion = "${version}"
    featureProvider = 'Dirk Fauth'

    defaultQualifier = ''
    useBndHashQualifiers = false
    useFeatureHashQualifiers = false
    defaultQualifierMap.prefix = ''
		
	fetchSources = true

	feature(id: 'org.fipro.test.feature', name: 'Test') {
		
		// define what's in the feature
		plugin "${groupId}:test-service:${version}", {
			// exclude this transitive dependency
			exclude group: 'org.slf4j', module: 'slf4j-api'
		}
	}

}`

**Comment by stempler** [comment]
I have an old but proven build [here](https://github.com/halestudio/hale-platform/blob/8fc1490246b88b0aacb81d073287b97911d27eb6/build.gradle#L805), that still uses Gradle 1.11. I confirmed that there are no source bundles in the features of the generated update site.

"platform feature" relates to the special feature that is generated when using the `generatePlatformFeature` setting (see [settings](https://github.com/stempler/bnd-platform#plugin-settings)). It simply includes everything.

**Comment by stempler** [comment]
What kind of dependency is your plugin? Is it also built in the project and then published locally or is it an external dependency?

**Comment by fipro78** [comment]
Hm, in the description it says it defaults to true, which would mean it would be a platform feature right? But if I try to set it to false (or set it anyway) I get an exception that the property is not known generatePlatformFeature.

It is a bundle that is generated in another project and I need to build a p2 site for the integration into an Eclipse project.

**Comment by fipro78** [comment]
I updated to version 1.7 and set generatePlatformFeature to false and it seems to work now.

Thanks for the support! I will test in production in our systems and close the ticket once verified.

**Comment by stempler** [comment]
I think the root of the problem is the platform feature and these lines:

```
    featureId = 'org.fipro.test.feature'
    featureName = 'Test Services'
    featureVersion = "${version}"
    featureProvider = 'Dirk Fauth'
```

These lines assign the same ID to the platform feature as you use for your custom defined feature. Due to that clash all bundles end up in the feature.

So it should be enough to disable the platform feature (and you can also remove the lines above as they configure the platform feature).

**Comment by SimonScholz** [comment]
Hey Dirk my friend,

please have a look at this sample: https://github.com/OpenReqEU/eclipse-plugin-vogella/blob/master/eclipse/dependencies/build.gradle

By using `generatePlatformFeature = false` I turned off the platform feature ;-)

**Comment by SimonScholz** [comment]
Btw. since version 1.7 you can also omit the `eclipseHome` property because of https://github.com/stempler/bnd-platform/pull/46

**Comment by fipro78** [comment]
Hi,
we verified the changes in the configuration and it works. So it was an error in our configuration. Disabling `generatePlatformFeature` and for correctness correcting the `featureId` solved it. 

Thanks for the support!

@SimonScholz 
Unfortunately omitting `eclipseHome` does not work in scenarios where bintray is blocked by firewall rules.
